### ISSUE TITLE
be most specific with CSS selectors

### ISSUE THREAD

**Issue by NoureldeanSaed** [FACG4/RIAA#28]
When you make a change in CSS you have to be much more specific than :
```css
.contact_us div {
    width: 95%;
    margin: 0 auto;
  }

  .info *{
    width: 100%;
    height: 30px;
    font-size: 20px;
  }
```
in order to prevent any code overlapping between you and your teammates.
